### ISSUE TITLE
Is pytest-cov dependency needed?

### ISSUE THREAD

**Issue by etingof** [vkrizan/python-smclip#1]
The tool seems to call two coverage instrumentations in .travis.yml: pytest-cov and coverage. Is it done deliberately? Here is a potentially relevant [discussion](http://stackoverflow.com/questions/16404716/using-py-test-with-coverage-doesnt-include-imports).

Also consider adding requirements.txt. ;)

**Comment by vkrizan** [comment]
This is straight from the codecov examples: https://github.com/codecov/example-python#using-pytest

`requirements.txt` file is not yet needed, since there are no dependencies, other than for tests which are defined in [`setup.py`](https://github.com/vkrizan/python-smclip/blob/master/setup.py#L45).
